title: BlackFriday.com.br
description: >- # Isso aqui vc tem q pedir pro andré!
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-postcss

header_pages:
  - page:
      cta: Cadastre-se
      href: /cadastro
  - page:
      cta: Blog
      href: /blog

postcss:
  cache: false
  
sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
