title: BlackFriday.com.br
description: >- # Isso aqui tem q pedir pro andré!
baseurl: /blackfriday
url: https://lucasbortolini.github.io

# My variables

header_pages:
  - page:
      cta: Cadastre-se
      href: /cadastro
  - page:
      cta: Blog
      href: /blog
  - page:
      cta: Anuncie
      href: /Anuncie

collections:
  pages:
    output: true
    permalink: /:path/
    order:
      - welcome.md

# Configurations

theme: minima

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false
  
sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json

include: ["node_modules/tailwindcss"]
