title: Black Friday 2021
description: Black Friday 2021 - O primeiro e original do Brasil. As melhores promoções e ofertas de produtos das grandes marcas, em um único lugar.
baseurl: /blackfriday
url: https://lucasbortolini.github.io
logo: assets/images/logo.svg
lang: pt-br

header:
  pages:
    - cta: Cadastre-se
      href: "#"
    - cta: Blog
      href: "#blog"
    - cta: Anuncie
      href: /anuncie

footer:
  pages:
    - cta: Termos de Uso
      href: https://www.blackfriday.com.br/static/tpl/frontend/Termos-de-Uso.pdf
    - cta: Política de Privacidade
      href: /politica-de-privacidade
    - cta: Perguntas Frequentes
      href: /perguntas-frequentes
    - cta: Sala de Imprensa
      href: /sala-de-imprensa
    - cta: Anuncie
      href: /anuncie
  images:
    - src: assets/images/BuscaDescontos.png
      href: https://www.buscadescontos.com.br
      alt: Busca Descontos
    - src: assets/images/BlackFriday.png
      href: "#"
      alt: Black Friday 2021
    - src: assets/images/DiadoFreteGratis.png
      href: https://www.diadofretegratis.com.br/
      alt: Black Friday Discount 2021
    - src: assets/images/CyberMonday.png
      href: http://www.cybermondaybrasil.com.br/
      alt: Cyber Monday Brasil 2021
    - src: assets/images/BrasilGameDay.png
      href: http://www.brasilgameday.com.br/
      alt: Brasil Game Day
  text: O Busca Descontos não vende produtos, é um site gratuito para os internautas. Como um agregador de ofertas não podemos garantir o preço e a disponibilidade das ofertas. As imagens são meramente ilustrativas. Caso haja diferença de preço ou descrição do produto entre o site do Busca Descontos e o site da loja, a condição válida e praticada será a do site do lojista. Sempre confira o preço e as condições diretamente no site da loja. Veja também as regras de entrega gratuita, parcelamento e política de vendas no site do lojista. Asofertas, condições de venda e preços dos varejistas podem ser alteradas ou interrompidas a qualquer momento, sem aviso prévio. Confira sempre o preço na página do produto da loja direcionada antes de efetuar a compra. A entrega do pedido é condicionada a disponibilidade do estoque do lojista e não está sob o controle dasoperações do buscadescontos.com.br.

collections:
  pages:
    output: true
  blog: 
    output: true

theme: minima

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-coffeescript

postcss:
  cache: false
  
sass:  
  style: compressed
  load_paths:
    - _sass
    - node_modules

exclude:
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json

keep_files: [assets/images]

include: ["node_modules/tailwindcss"]
