title: BlackFriday.com.br
description: >- # Isso aqui tem q pedir pro andré!
baseurl: ""
url: ""

# My variables

header_pages:
  - page:
      cta: Cadastre-se
      href: /cadastro
  - page:
      cta: Blog
      href: /blog
  - page:
      cta: Anuncie
      href: /Anuncie

# Configurations

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-postcss 

postcss:
  cache: false
  
sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json

include: ["node_modules/tailwindcss"]