title: BlackFriday.com.br
description: >- # Isso aqui tem q pedir pro andré!
baseurl: /blackfriday
url: https://lucasbortolini.github.io
logo: assets/images/logo.svg
banner: assets/images/appliances.png
lang: pt-br

# My variables

header_pages:
  - page:
      cta: Cadastre-se
      href: /cadastro
  - page:
      cta: Blog
      href: /blog
  - page:
      cta: Anuncie
      href: /anuncie

footer:
  pages:
    - page:
        cta: Termos de Uso
        href: /termos-de-uso
    - page:
        cta: Política de Privacidade
        href: /politica-de-privacidade
    - page:
        cta: Perguntas Frequentes
        href: /perguntas-frequentes
    - page:
        cta: Sala de Imprensa
        href: /sala-de-imprensa
    - page:
        cta: Anuncie
        href: /anuncie
  text: O Busca Descontos não vende produtos, é um site gratuito para os internautas. Como um agregador de ofertas não podemos garantir o preço e a disponibilidade das ofertas. As imagens são meramente ilustrativas. Caso haja diferença de preço ou descrição do produto entre o site do Busca Descontos e o site da loja, a condição válida e praticada será a do site do lojista. Sempre confira o preço e as condições diretamente no site da loja. Veja também as regras de entrega gratuita, parcelamento e política de vendas no site do lojista. Asofertas, condições de venda e preços dos varejistas podem ser alteradas ou interrompidas a qualquer momento, sem aviso prévio. Confira sempre o preço na página do produto da loja direcionada antes de efetuar a compra. A entrega do pedido é condicionada a disponibilidade do estoque do lojista e não está sob o controle dasoperações do buscadescontos.com.br.

when:
  image: assets/images/when.png
  paragraphs: 
    - Em 2021 a Black Friday será no dia 26 de Novembro. A data mais esperada com ofertas do Brasil está chegando!
    - O evento acontece sempre na sexta-feira, após o feriado de ação de graças nos Estados Unidos.
    - Coloque a data no seu calendário e prepare-se para se juntar a milhões de consumidores em todo o mundo que irão fazer negócios incríveis comprando os produtos de seus sonhos.

what:
  image: assets/images/what.png
  paragraphs:
    - A tradução de Black Friday é "Sexta feira Negra". Na prática ela tem o significado da maior data de ofertas do Brasil!
    - A origem exata ninguém sabe dizer ao certo, há quem diga que a expressão nasceu no final do século XIX após duas instituições financeiras terem quebrado no mesmo dia em plena corrida do ouro. Coincidentemente, em uma sexta-feira.
    - Outra teoria conhecida é que o termo foi criado por policiais da Filadélfia na década de 60 para se referir ao dia após o feriado do Dia de Ação de Graças em que o trânsito se tornou um caos. Graças a isso, surgiu então uma grande oportunidade de venda para os lojistas que se aproveitavam disso e faziam diversas promoções para atrair quem passasse por lá.
    - Essa referência ao trânsito logo se expandiu e se tornou uma expressão local às ofertas, se transformando em uma grande tradição de compras.
    - No Brasil, a Black Friday chegou em 2011 com o portal Busca Descontos, e desde então cresce exponencialmente, batendo recorde de vendas ano a ano.
    - Diferentemente dos Estados Unidos, a Black Friday no Brasil começou como um evento exclusivamente online que passou para o varejo físico e atualmente atinge desde o pequeno até o grande varejista.
 
collections:
  pages:
    output: true
    permalink: /:path/
    order:
      - welcome.md

# Configurations

theme: minima

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false
  
sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - .jekyll-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package-lock.json

keep_files: [assets/images]

include: ["node_modules/tailwindcss"]
